import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "fr",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Sidebar nav
    "nav.dashboard": "Dashboard",
    "nav.dispatch": "Dispatch",
    "nav.accounts": "Comptes",
    "nav.onboarding": "Onboarding",
    "nav.providers": "Prestataires",
    "nav.fleet_managers": "Gestionnaires",
    "nav.interventions": "Interventions",
    "nav.technicians": "Techniciens",
    "nav.map": "Carte",
    "nav.billing": "Facturation",
    "nav.analytics": "Analytics",
    "nav.audit_logs": "Audit Logs",
    "nav.documentation": "Documentation",
    "nav.guide": "Guide",
    "nav.roles": "Rôles",
    "nav.settings": "Paramètres",
    "nav.navigation": "Navigation",

    // Header
    "header.search": "Rechercher...",
    "header.toggle_theme": "Changer le thème",
    "header.toggle_sidebar": "Basculer la sidebar",

    // Roles
    "role.admin": "Admin",
    "role.moderator": "Modérateur",
    "role.user": "Utilisateur",

    // Sidebar footer
    "sidebar.upgrade": "Upgrade Pro",
    "sidebar.upgrade_desc": "Débloquez l'analytics avancé et les rapports en temps réel.",

    // Dashboard
    "dashboard.greeting": "Bonjour, Admin 👋",
    "dashboard.subtitle": "Voici un aperçu de votre plateforme aujourd'hui.",
    "dashboard.total_accounts": "Comptes totaux",
    "dashboard.pending": "En attente",
    "dashboard.active_interventions": "Interventions actives",
    "dashboard.monthly_revenue": "Revenu du mois",
    "dashboard.system_operational": "Système opérationnel",
    "dashboard.interventions": "Interventions",
    "dashboard.last_30_days": "30 derniers jours",
    "dashboard.this_week": "Cette semaine",
    "dashboard.per_day": "Interventions par jour",
    "dashboard.total": "Total",
    "dashboard.completed": "Terminées",
    "dashboard.pending_approval": "En attente d'approbation",
    "dashboard.requests": "demandes",
    "dashboard.view_all": "Tout voir",
    "dashboard.recent_activity": "Activité récente",
    "dashboard.recent_activity_desc": "Dernières actions sur la plateforme",
    "dashboard.history": "Historique",
    "dashboard.review": "Examiner",
    "dashboard.this_month": "ce mois",
    "dashboard.today": "aujourd'hui",
    "dashboard.vs_last_month": "vs mois dernier",
    "dashboard.new": "nouveaux",

    // Dispatch
    "dispatch.title": "Dispatch Center",
    "dispatch.subtitle": "Assignez et suivez les interventions en temps réel",
    "dispatch.scope_note": "Le Dispatch Center assigne les missions aux entreprises prestataires. Le choix du technicien terrain est géré par l'entreprise de service choisie.",
    "dispatch.unassigned": "non assignée",
    "dispatch.unassigned_plural": "non assignées",
    "dispatch.in_progress": "en cours",
    "dispatch.assign": "Assigner",
    "dispatch.advance": "Avancer",
    "dispatch.assign_provider": "Assigner un prestataire",
    "dispatch.intervention": "Intervention",
    "dispatch.available_provider": "Prestataire disponible",
    "dispatch.select_provider": "Sélectionner un prestataire",
    "dispatch.mission_assigned": "Mission assignée",
    "dispatch.status_updated": "Statut mis à jour",
    "dispatch.providers": "Prestataires",
    "dispatch.no_intervention": "Aucune intervention",
    "dispatch.all": "Tous",
    "dispatch.search": "Rechercher...",
    "dispatch.urgency_normal": "Normal",
    "dispatch.urgency_high": "Urgent",
    "dispatch.urgency_critical": "Critique",

    // Interventions
    "interventions.title": "Interventions",
    "interventions.subtitle": "Suivez et gérez toutes les interventions de la plateforme.",
    "interventions.scope_note": "L'assignation finale d'un technicien spécifique est gérée en interne par le prestataire de services assigné.",
    "interventions.new": "Nouvelle intervention",
    "interventions.created": "Créé",
    "interventions.assigned": "Assigné",
    "interventions.en_route": "En route",
    "interventions.arrived": "Arrivé",
    "interventions.in_progress": "En cours",
    "interventions.completed": "Terminé",
    "interventions.cancelled": "Annulé",
    "interventions.fleet_manager": "Gestionnaire de flotte",
    "interventions.service_provider": "Prestataire",
    "interventions.technician": "Technicien",
    "interventions.vehicle_plate": "Plaque",
    "interventions.vehicle_model": "Modèle",
    "interventions.vehicle_year": "Année",
    "interventions.service_type": "Type de service",
    "interventions.location": "Localisation",
    "interventions.timeline": "Timeline complète",
    "interventions.details": "Détails",
    "interventions.advance_status": "Avancer le statut",
    "interventions.cancel": "Annuler l'intervention",
    "interventions.delete": "Supprimer",
    "interventions.confirm_delete": "Supprimer l'intervention",
    "interventions.delete_warning": "Êtes-vous sûr de vouloir supprimer {id} ? Cette action est irréversible.",
    "interventions.filter_by_status": "Filtrer par statut",
    "interventions.filter_by_date": "Filtrer par date",
    "interventions.reset_filters": "Réinitialiser",
    "interventions.no_results": "Aucune intervention trouvée",
    "interventions.no_results_desc": "Modifiez vos filtres ou votre recherche",
    "interventions.all": "Toutes",
    "interventions.start_date": "Début",
    "interventions.end_date": "Fin",
    "interventions.active": "actives",
    "interventions.finished": "terminées",
    "interventions.search": "Rechercher par ID, nom...",
    "interventions.of_total": "sur",
    "interventions.move_to": "Passer à «\u00A0{status}\u00A0»",
    "interventions.created_success": "Intervention créée",
    "interventions.status_updated": "Statut mis à jour",
    "interventions.cancelled_success": "Intervention annulée",
    "interventions.deleted_success": "Intervention supprimée",
    "interventions.required_fields": "Champs requis",
    "interventions.fill_all": "Veuillez remplir tous les champs.",
    "interventions.vehicle": "Véhicule",
    "interventions.create_intervention": "Create the intervention",
    "interventions.location_type": "Location type",
    "interventions.location_address": "Address / Free entry",
    "interventions.location_gps": "GPS Coordinates (lat, lng)",
    "interventions.get_my_location": "My position",
    "interventions.location_placeholder_gps": "Ex: 48.8566, 2.3522",
    "interventions.location_type": "Type de localisation",
    "interventions.location_address": "Adresse / Saisie libre",
    "interventions.location_gps": "Coordonnées GPS (lat, lng)",
    "interventions.get_my_location": "Ma position",
    "interventions.location_placeholder_gps": "Ex: 48.8566, 2.3522",

    // Onboarding
    "onboarding.title": "Onboarding",
    "onboarding.subtitle": "Management and validation of registration files",
    "onboarding.scope_note": "Validation of technicians and drivers in this file confirms their belonging to the company. They do not have individual platform access at this stage.",
    "onboarding.refresh": "Refresh",
    "onboarding.all_status": "All statuses",
    "onboarding.all_types": "All types",
    "onboarding.sp": "Providers (SP)",
    "onboarding.fleet": "Fleet Managers",
    "onboarding.search_placeholder": "Search company, email...",
    "onboarding.view_dossier": "View dossier",
    "onboarding.details_title": "Dossier Details",
    "onboarding.details_desc": "Verify the information provided before validating the account.",
    "onboarding.loading_data": "Loading data...",
    "onboarding.company_info": "Company Information",
    "onboarding.company_name": "Company Name",
    "onboarding.account_type": "Account Type",
    "onboarding.code": "Code",
    "onboarding.zone": "Zone",
    "onboarding.overview": "Overview",
    "onboarding.tech": "Technicians",
    "onboarding.drivers": "Drivers",
    "onboarding.services": "Services",
    "onboarding.vehicles": "Vehicles",
    "onboarding.contact_email": "Contact Email",
    "onboarding.contact_phone": "Phone",
    "onboarding.no_member": "No members registered.",
    "onboarding.no_asset": "No items registered.",
    "onboarding.choose_service": "Choose a service",
    "onboarding.base_price": "Base price",
    "onboarding.add": "Add",
    "onboarding.full_name": "Full name",
    "onboarding.skill": "Skill",
    "onboarding.license_no": "License No",
    "onboarding.label": "Vehicle label",
    "onboarding.plate": "Plate",
    "onboarding.vehicle_type": "Vehicle type",
    "onboarding.activation_title": "Provider presence activation",
    "onboarding.map_name": "Name displayed on map",
    "onboarding.lat_opt": "Optional latitude",
    "onboarding.lng_opt": "Optional longitude",
    "onboarding.service_ids_opt": "Optional service IDs (comma separated)",
    "onboarding.make_available": "Make provider available after approval",
    "onboarding.activation_note": "If coordinates or services are left empty, the backend will use the zone and available pricing services.",
    "onboarding.reject": "Reject dossier",
    "onboarding.approve": "Approve and Activate",
    "onboarding.submit": "Submit for review",
    "onboarding.submit_note_sp": "Add at least one technician and one priced service before submission.",
    "onboarding.submit_note_fleet": "Add at least one driver and one vehicle before submission.",
    "onboarding.reject_title": "Reject dossier",
    "onboarding.reject_desc": "Please indicate the reason for rejection. It will be sent to the applicant.",
    "onboarding.reject_placeholder": "Ex: Missing documents, incorrect information...",
    "onboarding.confirm_reject": "Confirm rejection",
    "onboarding.status_draft": "Draft",
    "onboarding.status_pending": "In review",
    "onboarding.status_approved": "Approved",
    "onboarding.status_rejected": "Rejected",

    // Onboarding
    "onboarding.title": "Onboarding",
    "onboarding.subtitle": "Gestion et validation des dossiers d'inscription",
    "onboarding.scope_note": "La validation des techniciens et conducteurs dans ce dossier confirme leur appartenance à l'entreprise. Ils ne disposent pas d'accès plateforme individuel à ce stade.",
    "onboarding.refresh": "Actualiser",
    "onboarding.all_status": "Tous les statuts",
    "onboarding.all_types": "Tous les types",
    "onboarding.sp": "Prestataires (SP)",
    "onboarding.fleet": "Gestionnaires de flotte",
    "onboarding.search_placeholder": "Rechercher une entreprise, email...",
    "onboarding.view_dossier": "Voir le dossier",
    "onboarding.details_title": "Détails du dossier",
    "onboarding.details_desc": "Vérifiez les informations fournies avant de valider le compte.",
    "onboarding.loading_data": "Chargement des données...",
    "onboarding.company_info": "Informations Entreprise",
    "onboarding.company_name": "Raison sociale",
    "onboarding.account_type": "Type de compte",
    "onboarding.code": "Code",
    "onboarding.zone": "Zone",
    "onboarding.overview": "Vue d'ensemble",
    "onboarding.tech": "Techniciens",
    "onboarding.drivers": "Conducteurs",
    "onboarding.services": "Services",
    "onboarding.vehicles": "Véhicules",
    "onboarding.contact_email": "Email de contact",
    "onboarding.contact_phone": "Téléphone",
    "onboarding.no_member": "Aucun membre enregistré.",
    "onboarding.no_asset": "Aucun élément enregistré.",
    "onboarding.choose_service": "Choisir un service",
    "onboarding.base_price": "Prix de base",
    "onboarding.add": "Ajouter",
    "onboarding.full_name": "Nom complet",
    "onboarding.skill": "Spécialité",
    "onboarding.license_no": "No permis",
    "onboarding.label": "Libellé véhicule",
    "onboarding.plate": "Immatriculation",
    "onboarding.vehicle_type": "Type véhicule",
    "onboarding.activation_title": "Activation provider presence",
    "onboarding.map_name": "Nom affiché sur la carte",
    "onboarding.lat_opt": "Latitude optionnelle",
    "onboarding.lng_opt": "Longitude optionnelle",
    "onboarding.service_ids_opt": "Service IDs optionnels (séparés par virgule)",
    "onboarding.make_available": "Rendre le provider disponible après approbation",
    "onboarding.activation_note": "Si les coordonnées ou les services sont laissés vides, le backend utilisera la zone et les services pricing disponibles.",
    "onboarding.reject": "Rejeter le dossier",
    "onboarding.approve": "Approuver et Activer",
    "onboarding.submit": "Soumettre pour revue",
    "onboarding.submit_note_sp": "Ajoutez au moins un technicien et un service tarifé avant soumission.",
    "onboarding.submit_note_fleet": "Ajoutez au moins un conducteur et un véhicule avant soumission.",
    "onboarding.reject_title": "Rejeter le dossier",
    "onboarding.reject_desc": "Veuillez indiquer la raison du rejet. Celle-ci sera transmise au demandeur.",
    "onboarding.reject_placeholder": "Ex: Documents manquants, informations erronées...",
    "onboarding.confirm_reject": "Confirmer le rejet",
    "onboarding.status_draft": "Brouillon",
    "onboarding.status_pending": "En révision",
    "onboarding.status_approved": "Approuvé",
    "onboarding.status_rejected": "Rejeté",
    "interventions.select": "Sélectionner",
    "interventions.waiting": "En attente",
    "interventions.col_id": "ID",
    "interventions.col_manager": "Gestionnaire",
    "interventions.col_provider": "Prestataire",
    "interventions.col_technician": "Technicien",
    "interventions.col_service": "Service",
    "interventions.col_status": "Statut",
    "interventions.col_progress": "Progression",
    "interventions.col_date": "Date",

    // Accounts
    "accounts.title": "Comptes",
    "accounts.subtitle": "Gérez les inscriptions des prestataires et gestionnaires.",
    "accounts.new": "Nouveau compte",
    "accounts.approved": "Approuvé",
    "accounts.pending": "En attente",
    "accounts.rejected": "Rejeté",
    "accounts.approve": "Approuver",
    "accounts.reject": "Rejeter",
    "accounts.company": "Entreprise",
    "accounts.type": "Type",
    "accounts.email": "Email",
    "accounts.phone": "Téléphone",
    "accounts.reg_number": "N° d'enregistrement",
    "accounts.submitted": "Soumis le",
    "accounts.status": "Statut",
    "accounts.details": "Détails du compte",
    "accounts.all": "Tous",
    "accounts.all_types": "Tous",
    "accounts.sp_type": "Prestataires",
    "accounts.fleet_type": "Gestionnaires",
    "accounts.all_status": "Tous les statuts",
    "accounts.actions": "Actions",
    "accounts.search": "Rechercher par nom, email...",
    "accounts.export_csv": "Export CSV",
    "accounts.of_total": "sur",
    "accounts.prev": "Précédent",
    "accounts.next": "Suivant",
    "accounts.sp": "Prestataire",
    "accounts.fleet": "Gestionnaire",
    "accounts.edit_account": "Modifier le compte",
    "accounts.new_account": "Nouveau compte",
    "accounts.company_required": "Entreprise *",
    "accounts.email_required": "Email *",
    "accounts.required_fields": "Champs requis",
    "accounts.required_msg": "Entreprise et email sont obligatoires.",
    "accounts.updated": "Compte mis à jour",
    "accounts.created": "Compte créé",
    "accounts.approved_msg": "Compte approuvé",
    "accounts.approved_desc": "Le compte a été activé.",
    "accounts.rejected_msg": "Compte rejeté",
    "accounts.rejected_desc": "Le compte a été refusé.",
    "accounts.deleted": "Compte supprimé",
    "accounts.delete_confirm": "Supprimer {name} ?",
    "accounts.delete_warning": "Cette action est irréversible.",
    "accounts.contact_info": "Informations de contact",
    "accounts.registration": "Enregistrement",

    // Providers
    "providers.title": "Prestataires",
    "providers.subtitle": "prestataires enregistrés.",
    "providers.scope_note": "Les techniciens affichés ici sont les ressources déclarées par le prestataire pour ses opérations internes.",
    "providers.new": "Ajouter",
    "providers.name": "Nom",
    "providers.contact": "Contact",
    "providers.city": "Ville",
    "providers.radius": "Rayon d'action",
    "providers.rating": "Évaluation",
    "providers.missions": "Missions",
    "providers.services": "Services",
    "providers.response_time": "Temps de réponse",
    "providers.details": "Détails du prestataire",
    "providers.all_status": "Tous",
    "providers.approved": "Approuvé",
    "providers.pending": "En attente",
    "providers.search": "Rechercher...",
    "providers.approved_label": "Approuvés",
    "providers.pending_label": "En attente",
    "providers.technicians": "Techniciens",
    "providers.completed": "Terminées",
    "providers.active": "Actives",
    "providers.view": "Voir",
    "providers.edit": "Modifier le prestataire",
    "providers.new_provider": "Nouveau prestataire",
    "providers.name_required": "Nom *",
    "providers.email_required": "Email *",
    "providers.required_fields": "Champs requis",
    "providers.required_msg": "Nom et email sont obligatoires.",
    "providers.updated": "Prestataire mis à jour",
    "providers.created": "Prestataire créé",
    "providers.deleted": "Prestataire supprimé",
    "providers.delete_confirm": "Supprimer {name} ?",
    "providers.delete_warning": "Cette action est irréversible.",
    "providers.coverage_zone": "Zone de couverture",
    "providers.performance": "Performance",
    "providers.member_since": "Membre depuis",

    // Fleet Managers
    "fleet.title": "Gestionnaires de flotte",
    "fleet.subtitle": "gestionnaires enregistrés.",
    "fleet.scope_note": "Les véhicules et chauffeurs recensés ici sont des ressources métier internes à la flotte. Ils ne disposent pas de compte d'accès direct par défaut.",
    "fleet.new": "Ajouter",
    "fleet.company": "Entreprise",
    "fleet.contact": "Contact",
    "fleet.city": "Ville",
    "fleet.vehicles": "Véhicules",
    "fleet.active": "Actif",
    "fleet.inactive": "Inactif",
    "fleet.all_status": "Tous",
    "fleet.details": "Détails du gestionnaire",
    "fleet.search": "Rechercher...",
    "fleet.active_label": "Actifs",
    "fleet.inactive_label": "Inactifs",
    "fleet.total_vehicles": "Véhicules totaux",
    "fleet.active_fleets": "Flottes actives",
    "fleet.active_interventions": "Interventions en cours",
    "fleet.col_company": "Entreprise",
    "fleet.col_contact": "Contact",
    "fleet.col_city": "Ville",
    "fleet.col_vehicles": "Véhicules",
    "fleet.col_active": "Actives",
    "fleet.col_total": "Total",
    "fleet.col_status": "Statut",
    "fleet.col_actions": "Actions",
    "fleet.edit": "Modifier le gestionnaire",
    "fleet.new_manager": "Nouveau gestionnaire",
    "fleet.company_required": "Entreprise *",
    "fleet.email_required": "Email *",
    "fleet.required_fields": "Champs requis",
    "fleet.required_msg": "Entreprise et email sont obligatoires.",
    "fleet.updated": "Gestionnaire mis à jour",
    "fleet.created": "Gestionnaire créé",
    "fleet.deleted": "Gestionnaire supprimé",
    "fleet.delete_confirm": "Supprimer {name} ?",
    "fleet.delete_warning": "Cette action est irréversible.",
    "fleet.member_since": "Membre depuis",
    "fleet.total_missions": "Total missions",
    "fleet.monthly_avg": "Moy. mensuelle",
    "fleet.fleet_types": "Types de flotte",

    // Technicians
    "tech.title": "Techniciens",
    "tech.subtitle": "Gérez et suivez les techniciens terrain",
    "tech.scope_note": "Cette vue recense les techniciens declares par les prestataires. La localisation et le statut operationnel restent derives des donnees provider/backend actuellement disponibles.",
    "tech.online": "En ligne",
    "tech.offline": "Hors ligne",
    "tech.on_job": "En mission",
    "tech.specialties": "Spécialités",
    "tech.provider": "Prestataire",
    "tech.missions_completed": "Missions terminées",
    "tech.current_mission": "Mission en cours",
    "tech.details": "Profil technicien",
    "tech.all": "Tous",
    "tech.joined": "Depuis",
    "tech.search": "Rechercher par nom, prestataire...",
    "tech.no_results": "Aucun technicien trouvé",
    "tech.no_results_desc": "Modifiez vos filtres",
    "tech.reset": "Réinitialiser",
    "tech.count": "technicien",
    "tech.count_plural": "techniciens",
    "tech.col_id": "ID",
    "tech.col_name": "Nom",
    "tech.col_provider": "Prestataire",
    "tech.col_status": "Statut",
    "tech.col_specialties": "Spécialités",
    "tech.col_missions": "Missions",
    "tech.col_rating": "Rating",
    "tech.col_location": "Localisation",
    "tech.rating": "Rating",

    // Map
    "map.title": "Carte de suivi",
    "map.subtitle": "Position en temps réel des prestataires",

    // Billing
    "billing.title": "Facturation",
    "billing.subtitle": "Suivi des paiements et revenus de la plateforme",
    "billing.invoices": "Factures",
    "billing.provider_revenue": "Revenus prestataires",
    "billing.paid": "Payé",
    "billing.pending": "En attente",
    "billing.overdue": "En retard",
    "billing.cancelled": "Annulé",
    "billing.total_paid": "Revenus (payés)",
    "billing.commissions": "Commissions gagnées",
    "billing.pending_amount": "En attente / retard",
    "billing.overdue_amount": "En retard",
    "billing.invoice_id": "Facture",
    "billing.date": "Date",
    "billing.client": "Client",
    "billing.provider": "Prestataire",
    "billing.amount": "Montant",
    "billing.commission": "Commission",
    "billing.status": "Statut",
    "billing.search": "Rechercher...",
    "billing.all": "Tous",
    "billing.no_results": "Aucune facture",
    "billing.no_results_desc": "Modifiez vos filtres",
    "billing.reset": "Réinitialiser",
    "billing.count": "facture",
    "billing.count_plural": "factures",
    "billing.intervention": "Intervention",
    "billing.col_paid_missions": "Missions payées",
    "billing.col_net_revenue": "Revenus nets",
    "billing.col_commissions": "Commissions prélevées",
    "billing.export_csv": "Export CSV",
    "billing.export_pdf": "Export PDF",
    "billing.csv_title": "Export CSV",
    "billing.csv_desc": "Factures exportées en CSV.",
    "billing.pdf_title": "Export PDF",
    "billing.pdf_desc": "Factures exportées en PDF.",

    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "Vue globale de la performance opérationnelle",
    "analytics.avg_time": "Temps moyen d'intervention",
    "analytics.missions_per_day": "Missions par jour",
    "analytics.success_rate": "Taux de réussite",
    "analytics.active_providers": "Prestataires actifs",
    "analytics.daily_missions": "Missions par jour",
    "analytics.response_time": "Temps de réponse moyen (min)",
    "analytics.zone_distribution": "Répartition par zone",
    "analytics.hourly_distribution": "Distribution horaire",
    "analytics.top_providers": "Prestataires les plus actifs",
    "analytics.by_service_type": "Interventions par type",
    "analytics.7_days": "7 jours",
    "analytics.30_days": "30 jours",
    "analytics.90_days": "90 jours",
    "analytics.total": "Total",
    "analytics.completed": "Complétées",
    "analytics.minutes": "minutes",
    "analytics.missions": "missions",
    "analytics.this_week": "cette semaine",
    "analytics.on_mission_today": "en mission aujourd'hui",
    "analytics.avg_time_label": "temps moyen",
    "analytics.export_csv": "Export CSV",
    "analytics.export_pdf": "Export PDF",
    "analytics.csv_title": "Export CSV",
    "analytics.csv_desc": "Rapport missions exporté en CSV.",
    "analytics.pdf_title": "Export PDF",
    "analytics.pdf_desc": "Rapport analytics exporté en PDF.",

    // Audit Logs
    "audit.title": "Journal d'audit",
    "audit.subtitle": "Historique de toutes les actions administratives",
    "audit.assign": "Assignation",
    "audit.status_change": "Changement statut",
    "audit.create": "Création",
    "audit.delete": "Suppression",
    "audit.update": "Modification",
    "audit.login": "Connexion",
    "audit.all_actions": "Tous",
    "audit.actor": "Acteur",
    "audit.action": "Action",
    "audit.description": "Description",
    "audit.target": "Objet",
    "audit.date": "Date",
    "audit.search": "Rechercher...",
    "audit.no_results": "Aucun log trouvé",
    "audit.no_results_desc": "Modifiez vos filtres",
    "audit.reset": "Réinitialiser",
    "audit.count": "entrée",
    "audit.count_plural": "entrées",

    // Settings
    "settings.title": "Paramètres",
    "settings.platform": "Plateforme",
    "settings.users": "Utilisateurs",
    "settings.notifications": "Notifications",
    "settings.system": "Système",
    "settings.platform_config": "Configuration de la plateforme",
    "settings.platform_name": "Nom de la plateforme",
    "settings.support_email": "Email de support",
    "settings.timezone": "Fuseau horaire",
    "settings.currency": "Devise",
    "settings.default_language": "Langue par défaut",
    "settings.coverage_radius": "Rayon de couverture par défaut (km)",
    "settings.auto_approve": "Approbation auto des prestataires",
    "settings.auto_approve_desc": "Sauter la vérification manuelle pour les nouvelles inscriptions",
    "settings.save_changes": "Enregistrer les modifications",
    "settings.saved": "enregistrés",
    "settings.saved_desc": "Vos modifications ont été appliquées.",
    "settings.invite_admin": "Inviter un admin",
    "settings.invite_email": "Adresse email",
    "settings.invite": "Inviter",
    "settings.admin_users": "Utilisateurs admin",
    "settings.remove_user": "Supprimer {name} ?",
    "settings.remove_desc": "L'accès admin sera révoqué immédiatement.",
    "settings.remove": "Supprimer",
    "settings.invitation_sent": "Invitation envoyée",
    "settings.invited_as": "Invité {email} en tant que {role}.",
    "settings.user_removed": "Utilisateur supprimé",
    "settings.user_removed_desc": "L'utilisateur admin a été supprimé.",
    "settings.email_required": "Email requis",
    "settings.email_required_desc": "Veuillez entrer une adresse email.",
    "settings.admin_notifications": "Notifications admin",
    "settings.notif_registrations": "Nouvelles inscriptions",
    "settings.notif_registrations_desc": "Alerte lors de l'inscription d'un prestataire ou gestionnaire",
    "settings.notif_interventions": "Alertes interventions",
    "settings.notif_interventions_desc": "Mises à jour critiques et escalades d'interventions",
    "settings.notif_errors": "Erreurs système",
    "settings.notif_errors_desc": "Notifications d'erreurs serveur et de downtime",
    "settings.notif_weekly": "Rapports hebdomadaires",
    "settings.notif_weekly_desc": "Résumé de l'activité de la plateforme chaque lundi",
    "settings.notif_daily": "Digest quotidien",
    "settings.notif_daily_desc": "Email récapitulatif quotidien des métriques clés",
    "settings.notif_slack": "Intégration Slack",
    "settings.notif_slack_desc": "Transférer les alertes vers un canal Slack",
    "settings.system_prefs": "Préférences système",
    "settings.session_timeout": "Timeout de session (minutes)",
    "settings.data_retention": "Rétention des données (jours)",
    "settings.maintenance_mode": "Mode maintenance",
    "settings.maintenance_desc": "Désactiver temporairement l'accès pour les non-admins",
    "settings.danger_zone": "Zone de danger",
    "settings.danger_desc": "Purger toutes les données ou réinitialiser la plateforme. Ces actions sont irréversibles.",
    "settings.reset_platform": "Réinitialiser la plateforme",
    "settings.reset_confirm": "Réinitialiser toute la plateforme ?",
    "settings.reset_desc": "Cela supprimera tous les comptes, interventions, factures et configuration. Cette action est irréversible.",
    "settings.reset_action": "Tout réinitialiser",

    // Profile
    "profile.title": "Mon Profil",
    "profile.subtitle": "Gérez vos informations personnelles.",
    "profile.personal_info": "Informations personnelles",
    "profile.update_success": "Profil mis à jour !",
    "profile.update_error": "Erreur lors de la mise à jour.",
    "profile.change_avatar": "Changer l'avatar",
    "profile.full_name": "Nom complet",
    "profile.email": "Email",
    "profile.edit": "Modifier",
    "profile.save": "Enregistrer",
    "profile.security": "Sécurité",
    "profile.password": "Mot de passe",
    "profile.password_desc": "Envoi d'un email de réinitialisation",
    "profile.change_password": "Changer",
    "profile.online": "En ligne",
    "profile.upload_error": "Erreur lors de l'upload.",
    "profile.avatar_updated": "Avatar mis à jour !",
    "profile.avatar_error": "Erreur lors de la mise à jour de l'avatar.",
    "profile.reset_sent": "Email de réinitialisation envoyé !",

    // Common
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.create": "Créer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.export": "Exporter",
    "common.loading": "Chargement...",
    "common.no_results": "Aucun résultat",
    "common.confirm": "Confirmer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.actions": "Actions",
    "common.status": "Statut",
    "common.name": "Nom",
    "common.email": "Email",
    "common.phone": "Téléphone",
    "common.date": "Date",
    "common.required_fields": "Champs requis",
    "common.confirm_delete": "Confirmer la suppression",
    "common.delete_warning": "Cette action est irréversible.",

    // Auth
    "auth.login": "Se connecter",
    "auth.signup": "S'inscrire",
    "auth.logout": "Se déconnecter",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.forgot_password": "Mot de passe oublié ?",
    "auth.no_account": "Pas de compte ?",
    "auth.has_account": "Déjà un compte ?",
    "auth.welcome": "Welcome back",
    "auth.welcome_subtitle": "Connectez-vous à votre compte",
    "auth.signup_title": "Créer un compte",
    "auth.signup_subtitle": "Inscrivez-vous pour accéder à la plateforme",
    "auth.forgot_title": "Mot de passe oublié",
    "auth.forgot_subtitle": "Entrez votre email pour réinitialiser",
    "auth.name": "Nom complet",
    "auth.verify_email": "Vérifiez votre email pour confirmer votre compte.",
    "auth.reset_sent": "Email de réinitialisation envoyé.",
    "auth.google": "Continuer avec Google",
    "auth.or": "ou",
    "auth.reset_password": "Réinitialiser le mot de passe",
    "auth.logging_in": "Connexion...",
    "auth.signing_up": "Inscription...",
    "auth.sending": "Envoi...",
    "auth.send_link": "Envoyer le lien",
    "auth.back_to_login": "Retour à la connexion",

    // Role guard
    "guard.restricted": "Accès restreint",
    "guard.no_permission": "Vous n'avez pas les permissions nécessaires pour accéder à cette page.",
    "guard.required_roles": "Rôles requis",

    // Admin Roles
    "roles.title": "Gestion des rôles",
    "roles.subtitle": "Gérez les permissions des utilisateurs de la plateforme.",
    "roles.search": "Rechercher un utilisateur...",
    "roles.user_col": "Utilisateur",
    "roles.current_role": "Rôle actuel",
    "roles.action": "Action",
    "roles.yourself": "Vous-même",
    "roles.updated": "Rôle mis à jour !",
    "roles.assigned": "Rôle attribué !",
    "roles.admins": "Admins",
    "roles.moderators": "Modérateurs",
    "roles.users": "Utilisateurs",
    "roles.no_user": "Aucun utilisateur trouvé.",
    "roles.access_denied": "Accès refusé",
    "roles.admin_required": "Vous devez avoir le rôle Admin pour accéder à cette page.",

    // Not found
    "notfound.title": "404",
    "notfound.message": "Oups ! Page non trouvée",
    "notfound.back_home": "Retour à l'accueil",

    // Status labels
    "status.pending": "En attente",
    "status.assigned": "Assigné",
    "status.en_route": "En route",
    "status.arrived": "Arrivé",
    "status.in_progress": "En cours",
    "status.completed": "Terminé",
    "status.cancelled": "Annulé",
    "status.approved": "Approuvé",
    "status.rejected": "Rejeté",
    "status.active": "Actif",
    "status.inactive": "Inactif",
    "status.paid": "Payé",
    "status.overdue": "En retard",

    // Days
    "day.mon": "Lun",
    "day.tue": "Mar",
    "day.wed": "Mer",
    "day.thu": "Jeu",
    "day.fri": "Ven",
    "day.sat": "Sam",
    "day.sun": "Dim",

    // Activity
    "activity.account_created": "Compte créé",
    "activity.submitted_review": "Soumis pour révision",
    "activity.account_rejected": "Compte rejeté",
    "activity.ago_5min": "Il y a 5 min",
    "activity.ago_23min": "Il y a 23 min",
    "activity.ago_1h": "Il y a 1h",
    "activity.ago_3h": "Il y a 3h",
    "activity.ago_5h": "Il y a 5h",

    // Accounts
    "accounts.title": "Comptes",
    "accounts.subtitle": "Gérez les inscriptions des prestataires et gestionnaires.",
    "accounts.new": "Nouveau compte",
    "accounts.search": "Rechercher par nom, email...",
    "accounts.filter_all": "Tous",
    "accounts.filter_sp": "Prestataires",
    "accounts.filter_fm": "Gestionnaires de flotte",
    "accounts.filter_all_status": "Tous les statuts",
    "accounts.export_csv": "Export CSV",
    "accounts.type_sp": "Prestataire",
    "accounts.type_fm": "Gestionnaire",
    "accounts.company": "Entreprise",
    "accounts.type": "Type",
    "accounts.email": "Email",
    "accounts.submitted": "Soumis",
    "accounts.status": "Statut",
    "accounts.actions": "Actions",
    "accounts.of": "sur",
    "accounts.accounts": "comptes",
    "accounts.previous": "Précédent",
    "accounts.next": "Suivant",
    "accounts.no_results": "Aucun compte trouvé",
    "accounts.no_results_desc": "Essayez de modifier vos filtres",
    "accounts.reset": "Réinitialiser",
    "accounts.edit_title": "Modifier le compte",
    "accounts.create_title": "Nouveau compte",
    "accounts.company_label": "Entreprise *",
    "accounts.company_placeholder": "Nom de l'entreprise",
    "accounts.type_label": "Type",
    "accounts.type_fleet": "Gestionnaire de flotte",
    "accounts.email_label": "Email *",
    "accounts.phone_label": "Téléphone",
    "accounts.cancel": "Annuler",
    "accounts.save": "Enregistrer",
    "accounts.create": "Créer",
    "accounts.required_fields": "Champs requis",
    "accounts.required_fields_desc": "Entreprise et email sont obligatoires.",
    "accounts.updated": "Compte mis à jour",
    "accounts.updated_desc": "a été modifié.",
    "accounts.created": "Compte créé",
    "accounts.created_desc": "ajouté en attente d'approbation.",
    "accounts.deleted": "Compte supprimé",
    "accounts.deleted_desc": "a été supprimé.",
    "accounts.approved_toast": "Compte approuvé",
    "accounts.approved_toast_desc": "Le compte a été activé.",
    "accounts.rejected_toast": "Compte rejeté",
    "accounts.rejected_toast_desc": "Le compte a été refusé.",
    "accounts.delete_title": "Supprimer",
    "accounts.delete_desc": "Cette action est irréversible. Le compte sera définitivement supprimé.",
    "accounts.delete": "Supprimer",
    "accounts.temp_password_title": "Compte créé avec succès",
    "accounts.temp_password_desc": "Veuillez noter le mot de passe temporaire ci-dessous. Il ne sera plus affiché.",
    "accounts.temp_password_label": "Mot de passe temporaire",
    "accounts.mobile_access_title": "Accès Application Mobile",
    "accounts.mobile_access_desc": "Informations nécessaires pour la connexion de l'entreprise à l'application terrain.",
    "accounts.company_code": "Code Entreprise",
    "accounts.reset_password": "Réinitialiser le mot de passe",
    "accounts.reset_password_confirm": "Voulez-vous réinitialiser le mot de passe de ce compte ? Un nouveau mot de passe temporaire sera généré.",
    "accounts.copy_all": "Copier les infos de connexion",
    "accounts.credentials_copied": "Informations copiées !",
    "accounts.technicians_tab": "Techniciens",
    "accounts.services_tab": "Services",
    "accounts.documents_tab": "Documents",
    "accounts.reg_number": "N° d'inscription",
    "accounts.submission_date": "Date de soumission",
    "accounts.approve": "Approuver",
    "accounts.edit": "Modifier",
    "accounts.view": "Voir",
    "accounts.reject": "Rejeter",
    "accounts.technicians_count": "techniciens enregistrés",
    "accounts.services_list": "Remorquage, Changement pneu, Batterie",
    "accounts.services_pricing": "Tarifs : 45€ – 180€ par intervention",
    "accounts.documents_count": "documents téléchargés",
    "accounts.documents_list": "Assurance, Licence, Immatriculation, Certificat",

    // Providers
    "providers.title": "Prestataires",
    "providers.registered": "prestataires enregistrés.",
    "providers.search": "Rechercher...",
    "providers.all": "Tous",
    "providers.approved": "Approuvés",
    "providers.pending": "En attente",
    "providers.add": "Ajouter",
    "providers.status_approved": "Approuvé",
    "providers.status_pending": "En attente",
    "providers.technicians": "Techniciens",
    "providers.completed": "Terminées",
    "providers.active": "Actives",
    "providers.view": "Voir",
    "providers.edit_title": "Modifier le prestataire",
    "providers.create_title": "Nouveau prestataire",
    "providers.name_label": "Nom *",
    "providers.name_placeholder": "Nom du prestataire",
    "providers.contact_label": "Contact",
    "providers.contact_placeholder": "Nom du contact",
    "providers.email_label": "Email *",
    "providers.city_label": "Ville",
    "providers.services_label": "Services",
    "providers.cancel": "Annuler",
    "providers.save": "Enregistrer",
    "providers.create": "Créer",
    "providers.required_fields": "Champs requis",
    "providers.required_fields_desc": "Nom et email sont obligatoires.",
    "providers.updated": "Prestataire mis à jour",
    "providers.updated_desc": "modifié.",
    "providers.created": "Prestataire créé",
    "providers.created_desc": "ajouté.",
    "providers.deleted": "Prestataire supprimé",
    "providers.deleted_desc": "supprimé.",
    "providers.delete_title": "Supprimer",
    "providers.delete_desc": "Cette action est irréversible.",
    "providers.delete": "Supprimer",
    "providers.member_since": "Membre depuis",
    "providers.contact": "Contact",
    "providers.coverage_zone": "Zone de couverture",
    "providers.radius": "Rayon",
    "providers.performance": "Performance",
    "providers.completed_label": "Terminées",
    "providers.active_label": "Actives",
    "providers.technicians_label": "Techniciens",
    "providers.response_time": "Temps réponse",
    "providers.edit": "Modifier",

    // Fleet Managers
    "fleet.title": "Gestionnaires de flotte",
    "fleet.registered": "gestionnaires enregistrés.",
    "fleet.search": "Rechercher...",
    "fleet.all": "Tous",
    "fleet.active": "Actifs",
    "fleet.inactive": "Inactifs",
    "fleet.add": "Ajouter",
    "fleet.total_vehicles": "Véhicules totaux",
    "fleet.active_fleets": "Flottes actives",
    "fleet.ongoing_interventions": "Interventions en cours",
    "fleet.company": "Entreprise",
    "fleet.contact": "Contact",
    "fleet.city": "Ville",
    "fleet.vehicles": "Véhicules",
    "fleet.active_col": "Actives",
    "fleet.total": "Total",
    "fleet.status": "Statut",
    "fleet.actions": "Actions",
    "fleet.status_active": "Actif",
    "fleet.status_inactive": "Inactif",
    "fleet.edit_title": "Modifier le gestionnaire",
    "fleet.create_title": "Nouveau gestionnaire",
    "fleet.company_label": "Entreprise *",
    "fleet.contact_label": "Contact",
    "fleet.city_label": "Ville",
    "fleet.email_label": "Email *",
    "fleet.phone_label": "Téléphone",
    "fleet.vehicles_label": "Véhicules",
    "fleet.cancel": "Annuler",
    "fleet.save": "Enregistrer",
    "fleet.create": "Créer",
    "fleet.required_fields": "Champs requis",
    "fleet.required_fields_desc": "Entreprise et email sont obligatoires.",
    "fleet.updated": "Gestionnaire mis à jour",
    "fleet.updated_desc": "modifié.",
    "fleet.created": "Gestionnaire créé",
    "fleet.created_desc": "ajouté.",
    "fleet.deleted": "Gestionnaire supprimé",
    "fleet.deleted_desc": "supprimé.",
    "fleet.delete_title": "Supprimer",
    "fleet.delete_desc": "Cette action est irréversible.",
    "fleet.delete": "Supprimer",
    "fleet.member_since": "Membre depuis",
    "fleet.vehicles_stat": "Véhicules",
    "fleet.active_stat": "Actives",
    "fleet.total_missions": "Total missions",
    "fleet.monthly_avg": "Moy. mensuelle",
    "fleet.fleet_types": "Types de flotte",
    "fleet.edit": "Modifier",
  },
  en: {
    // Sidebar nav
    "nav.dashboard": "Dashboard",
    "nav.dispatch": "Dispatch",
    "nav.accounts": "Accounts",
    "nav.onboarding": "Onboarding",
    "nav.providers": "Providers",
    "nav.fleet_managers": "Fleet Managers",
    "nav.interventions": "Interventions",
    "nav.technicians": "Technicians",
    "nav.map": "Map",
    "nav.billing": "Billing",
    "nav.analytics": "Analytics",
    "nav.audit_logs": "Audit Logs",
    "nav.documentation": "Documentation",
    "nav.guide": "Guide",
    "nav.roles": "Roles",
    "nav.settings": "Settings",
    "nav.navigation": "Navigation",

    // Header
    "header.search": "Search...",
    "header.toggle_theme": "Toggle theme",
    "header.toggle_sidebar": "Toggle sidebar",

    // Roles
    "role.admin": "Admin",
    "role.moderator": "Moderator",
    "role.user": "User",

    // Sidebar footer
    "sidebar.upgrade": "Upgrade Pro",
    "sidebar.upgrade_desc": "Unlock advanced analytics and real-time reports.",

    // Dashboard
    "dashboard.greeting": "Hello, Admin 👋",
    "dashboard.subtitle": "Here's an overview of your platform today.",
    "dashboard.total_accounts": "Total accounts",
    "dashboard.pending": "Pending",
    "dashboard.active_interventions": "Active interventions",
    "dashboard.monthly_revenue": "Monthly revenue",
    "dashboard.system_operational": "System operational",
    "dashboard.interventions": "Interventions",
    "dashboard.last_30_days": "Last 30 days",
    "dashboard.this_week": "This week",
    "dashboard.per_day": "Interventions per day",
    "dashboard.total": "Total",
    "dashboard.completed": "Completed",
    "dashboard.pending_approval": "Pending approval",
    "dashboard.requests": "requests",
    "dashboard.view_all": "View all",
    "dashboard.recent_activity": "Recent activity",
    "dashboard.recent_activity_desc": "Latest actions on the platform",
    "dashboard.history": "History",
    "dashboard.review": "Review",
    "dashboard.this_month": "this month",
    "dashboard.today": "today",
    "dashboard.vs_last_month": "vs last month",
    "dashboard.new": "new",

    // Dispatch
    "dispatch.title": "Dispatch Center",
    "dispatch.subtitle": "Assign and track interventions in real-time",
    "dispatch.scope_note": "The Dispatch Center assigns missions to service provider companies. Field technician choice is managed by the chosen service company.",
    "dispatch.unassigned": "unassigned",
    "dispatch.unassigned_plural": "unassigned",
    "dispatch.in_progress": "in progress",
    "dispatch.assign": "Assign",
    "dispatch.advance": "Advance",
    "dispatch.assign_provider": "Assign a provider",
    "dispatch.intervention": "Intervention",
    "dispatch.available_provider": "Available provider",
    "dispatch.select_provider": "Select a provider",
    "dispatch.mission_assigned": "Mission assigned",
    "dispatch.status_updated": "Status updated",
    "dispatch.providers": "Providers",
    "dispatch.no_intervention": "No interventions",
    "dispatch.all": "All",
    "dispatch.search": "Search...",
    "dispatch.urgency_normal": "Normal",
    "dispatch.urgency_high": "Urgent",
    "dispatch.urgency_critical": "Critical",

    // Interventions
    "interventions.title": "Interventions",
    "interventions.subtitle": "Track and manage all platform interventions.",
    "interventions.scope_note": "The final assignment of a specific technician is managed internally by the assigned service provider.",
    "interventions.new": "New intervention",
    "interventions.created": "Created",
    "interventions.assigned": "Assigned",
    "interventions.en_route": "En route",
    "interventions.arrived": "Arrived",
    "interventions.in_progress": "In progress",
    "interventions.completed": "Completed",
    "interventions.cancelled": "Cancelled",
    "interventions.fleet_manager": "Fleet manager",
    "interventions.service_provider": "Service provider",
    "interventions.technician": "Technician",
    "interventions.vehicle_plate": "Plate",
    "interventions.vehicle_model": "Model",
    "interventions.vehicle_year": "Year",
    "interventions.service_type": "Service type",
    "interventions.location": "Location",
    "interventions.timeline": "Full timeline",
    "interventions.details": "Details",
    "interventions.advance_status": "Advance status",
    "interventions.cancel": "Cancel intervention",
    "interventions.delete": "Delete",
    "interventions.confirm_delete": "Delete intervention",
    "interventions.delete_warning": "Are you sure you want to delete {id}? This action is irreversible.",
    "interventions.filter_by_status": "Filter by status",
    "interventions.filter_by_date": "Filter by date",
    "interventions.reset_filters": "Reset",
    "interventions.no_results": "No interventions found",
    "interventions.no_results_desc": "Adjust your filters or search",
    "interventions.all": "All",
    "interventions.start_date": "Start",
    "interventions.end_date": "End",
    "interventions.active": "active",
    "interventions.finished": "completed",
    "interventions.search": "Search by ID, name...",
    "interventions.of_total": "of",
    "interventions.move_to": "Move to \"{status}\"",
    "interventions.created_success": "Intervention created",
    "interventions.status_updated": "Status updated",
    "interventions.cancelled_success": "Intervention cancelled",
    "interventions.deleted_success": "Intervention deleted",
    "interventions.required_fields": "Required fields",
    "interventions.fill_all": "Please fill in all fields.",
    "interventions.vehicle": "Vehicle",
    "interventions.create_intervention": "Create the intervention",
    "interventions.location_type": "Location type",
    "interventions.location_address": "Address / Free entry",
    "interventions.location_gps": "GPS Coordinates (lat, lng)",
    "interventions.get_my_location": "My position",
    "interventions.location_placeholder_gps": "Ex: 48.8566, 2.3522",
    "interventions.location_type": "Type de localisation",
    "interventions.location_address": "Adresse / Saisie libre",
    "interventions.location_gps": "Coordonnées GPS (lat, lng)",
    "interventions.get_my_location": "Ma position",
    "interventions.location_placeholder_gps": "Ex: 48.8566, 2.3522",

    // Onboarding
    "onboarding.title": "Onboarding",
    "onboarding.subtitle": "Management and validation of registration files",
    "onboarding.scope_note": "Validation of technicians and drivers in this file confirms their belonging to the company. They do not have individual platform access at this stage.",
    "onboarding.refresh": "Refresh",
    "onboarding.all_status": "All statuses",
    "onboarding.all_types": "All types",
    "onboarding.sp": "Providers (SP)",
    "onboarding.fleet": "Fleet Managers",
    "onboarding.search_placeholder": "Search company, email...",
    "onboarding.view_dossier": "View dossier",
    "onboarding.details_title": "Dossier Details",
    "onboarding.details_desc": "Verify the information provided before validating the account.",
    "onboarding.loading_data": "Loading data...",
    "onboarding.company_info": "Company Information",
    "onboarding.company_name": "Company Name",
    "onboarding.account_type": "Account Type",
    "onboarding.code": "Code",
    "onboarding.zone": "Zone",
    "onboarding.overview": "Overview",
    "onboarding.tech": "Technicians",
    "onboarding.drivers": "Drivers",
    "onboarding.services": "Services",
    "onboarding.vehicles": "Vehicles",
    "onboarding.contact_email": "Contact Email",
    "onboarding.contact_phone": "Phone",
    "onboarding.no_member": "No members registered.",
    "onboarding.no_asset": "No items registered.",
    "onboarding.choose_service": "Choose a service",
    "onboarding.base_price": "Base price",
    "onboarding.add": "Add",
    "onboarding.full_name": "Full name",
    "onboarding.skill": "Skill",
    "onboarding.license_no": "License No",
    "onboarding.label": "Vehicle label",
    "onboarding.plate": "Plate",
    "onboarding.vehicle_type": "Vehicle type",
    "onboarding.activation_title": "Provider presence activation",
    "onboarding.map_name": "Name displayed on map",
    "onboarding.lat_opt": "Optional latitude",
    "onboarding.lng_opt": "Optional longitude",
    "onboarding.service_ids_opt": "Optional service IDs (comma separated)",
    "onboarding.make_available": "Make provider available after approval",
    "onboarding.activation_note": "If coordinates or services are left empty, the backend will use the zone and available pricing services.",
    "onboarding.reject": "Reject dossier",
    "onboarding.approve": "Approve and Activate",
    "onboarding.submit": "Submit for review",
    "onboarding.submit_note_sp": "Add at least one technician and one priced service before submission.",
    "onboarding.submit_note_fleet": "Add at least one driver and one vehicle before submission.",
    "onboarding.reject_title": "Reject dossier",
    "onboarding.reject_desc": "Please indicate the reason for rejection. It will be sent to the applicant.",
    "onboarding.reject_placeholder": "Ex: Missing documents, incorrect information...",
    "onboarding.confirm_reject": "Confirm rejection",
    "onboarding.status_draft": "Draft",
    "onboarding.status_pending": "In review",
    "onboarding.status_approved": "Approved",
    "onboarding.status_rejected": "Rejected",
    "interventions.select": "Select",
    "interventions.waiting": "Waiting",
    "interventions.col_id": "ID",
    "interventions.col_manager": "Manager",
    "interventions.col_provider": "Provider",
    "interventions.col_technician": "Technician",
    "interventions.col_service": "Service",
    "interventions.col_status": "Status",
    "interventions.col_progress": "Progress",
    "interventions.col_date": "Date",

    // Accounts
    "accounts.title": "Accounts",
    "accounts.subtitle": "Manage provider and manager registrations.",
    "accounts.new": "New account",
    "accounts.approved": "Approved",
    "accounts.pending": "Pending",
    "accounts.rejected": "Rejected",
    "accounts.approve": "Approve",
    "accounts.reject": "Reject",
    "accounts.company": "Company",
    "accounts.type": "Type",
    "accounts.email": "Email",
    "accounts.phone": "Phone",
    "accounts.reg_number": "Registration number",
    "accounts.submitted": "Submitted",
    "accounts.status": "Status",
    "accounts.details": "Account details",
    "accounts.all": "All",
    "accounts.all_types": "All",
    "accounts.sp_type": "Service Providers",
    "accounts.fleet_type": "Fleet Managers",
    "accounts.all_status": "All Status",
    "accounts.actions": "Actions",
    "accounts.search": "Search by name, email...",
    "accounts.export_csv": "Export CSV",
    "accounts.of_total": "of",
    "accounts.prev": "Previous",
    "accounts.next": "Next",
    "accounts.sp": "Provider",
    "accounts.fleet": "Manager",
    "accounts.edit_account": "Edit account",
    "accounts.new_account": "New account",
    "accounts.company_required": "Company *",
    "accounts.email_required": "Email *",
    "accounts.required_fields": "Required fields",
    "accounts.required_msg": "Company and email are required.",
    "accounts.updated": "Account updated",
    "accounts.created": "Account created",
    "accounts.approved_msg": "Account approved",
    "accounts.approved_desc": "The account has been activated.",
    "accounts.rejected_msg": "Account rejected",
    "accounts.rejected_desc": "The account has been denied.",
    "accounts.deleted": "Account deleted",
    "accounts.delete_confirm": "Delete {name}?",
    "accounts.delete_warning": "This action is irreversible.",
    "accounts.contact_info": "Contact information",
    "accounts.registration": "Registration",

    // Providers
    "providers.title": "Providers",
    "providers.subtitle": "registered providers.",
    "providers.scope_note": "Technicians shown here are the resources declared by the provider for their internal operations.",
    "providers.new": "Add",
    "providers.name": "Name",
    "providers.contact": "Contact",
    "providers.city": "City",
    "providers.radius": "Coverage radius",
    "providers.rating": "Rating",
    "providers.missions": "Missions",
    "providers.services": "Services",
    "providers.response_time": "Response time",
    "providers.details": "Provider details",
    "providers.all_status": "All",
    "providers.approved": "Approved",
    "providers.pending": "Pending",
    "providers.search": "Search...",
    "providers.approved_label": "Approved",
    "providers.pending_label": "Pending",
    "providers.technicians": "Technicians",
    "providers.completed": "Completed",
    "providers.active": "Active",
    "providers.view": "View",
    "providers.edit": "Edit provider",
    "providers.new_provider": "New provider",
    "providers.name_required": "Name *",
    "providers.email_required": "Email *",
    "providers.required_fields": "Required fields",
    "providers.required_msg": "Name and email are required.",
    "providers.updated": "Provider updated",
    "providers.created": "Provider created",
    "providers.deleted": "Provider deleted",
    "providers.delete_confirm": "Delete {name}?",
    "providers.delete_warning": "This action is irreversible.",
    "providers.coverage_zone": "Coverage zone",
    "providers.performance": "Performance",
    "providers.member_since": "Member since",

    // Fleet Managers
    "fleet.title": "Fleet Managers",
    "fleet.subtitle": "registered managers.",
    "fleet.scope_note": "Vehicles and drivers listed here are internal fleet business resources. They do not have direct access accounts by default.",
    "fleet.new": "Add",
    "fleet.company": "Company",
    "fleet.contact": "Contact",
    "fleet.city": "City",
    "fleet.vehicles": "Vehicles",
    "fleet.active": "Active",
    "fleet.inactive": "Inactive",
    "fleet.all_status": "All",
    "fleet.details": "Manager details",
    "fleet.search": "Search...",
    "fleet.active_label": "Active",
    "fleet.inactive_label": "Inactive",
    "fleet.total_vehicles": "Total vehicles",
    "fleet.active_fleets": "Active fleets",
    "fleet.active_interventions": "Active interventions",
    "fleet.col_company": "Company",
    "fleet.col_contact": "Contact",
    "fleet.col_city": "City",
    "fleet.col_vehicles": "Vehicles",
    "fleet.col_active": "Active",
    "fleet.col_total": "Total",
    "fleet.col_status": "Status",
    "fleet.col_actions": "Actions",
    "fleet.edit": "Edit manager",
    "fleet.new_manager": "New manager",
    "fleet.company_required": "Company *",
    "fleet.email_required": "Email *",
    "fleet.required_fields": "Required fields",
    "fleet.required_msg": "Company and email are required.",
    "fleet.updated": "Manager updated",
    "fleet.created": "Manager created",
    "fleet.deleted": "Manager deleted",
    "fleet.delete_confirm": "Delete {name}?",
    "fleet.delete_warning": "This action is irreversible.",
    "fleet.member_since": "Member since",
    "fleet.total_missions": "Total missions",
    "fleet.monthly_avg": "Monthly avg.",
    "fleet.fleet_types": "Fleet types",

    // Technicians
    "tech.title": "Technicians",
    "tech.subtitle": "Manage and track field technicians",
    "tech.scope_note": "This view lists technicians declared by providers. Location and operational status are still derived from the provider/backend signals currently available.",
    "tech.online": "Online",
    "tech.offline": "Offline",
    "tech.on_job": "On job",
    "tech.specialties": "Specialties",
    "tech.provider": "Provider",
    "tech.missions_completed": "Completed missions",
    "tech.current_mission": "Current mission",
    "tech.details": "Technician profile",
    "tech.all": "All",
    "tech.joined": "Since",
    "tech.search": "Search by name, provider...",
    "tech.no_results": "No technicians found",
    "tech.no_results_desc": "Adjust your filters",
    "tech.reset": "Reset",
    "tech.count": "technician",
    "tech.count_plural": "technicians",
    "tech.col_id": "ID",
    "tech.col_name": "Name",
    "tech.col_provider": "Provider",
    "tech.col_status": "Status",
    "tech.col_specialties": "Specialties",
    "tech.col_missions": "Missions",
    "tech.col_rating": "Rating",
    "tech.col_location": "Location",
    "tech.rating": "Rating",

    // Map
    "map.title": "Tracking Map",
    "map.subtitle": "Real-time provider positions",

    // Billing
    "billing.title": "Billing",
    "billing.subtitle": "Track platform payments and revenue",
    "billing.invoices": "Invoices",
    "billing.provider_revenue": "Provider revenue",
    "billing.paid": "Paid",
    "billing.pending": "Pending",
    "billing.overdue": "Overdue",
    "billing.cancelled": "Cancelled",
    "billing.total_paid": "Revenue (paid)",
    "billing.commissions": "Commissions earned",
    "billing.pending_amount": "Pending / overdue",
    "billing.overdue_amount": "Overdue",
    "billing.invoice_id": "Invoice",
    "billing.date": "Date",
    "billing.client": "Client",
    "billing.provider": "Provider",
    "billing.amount": "Amount",
    "billing.commission": "Commission",
    "billing.status": "Status",
    "billing.search": "Search...",
    "billing.all": "All",
    "billing.no_results": "No invoices",
    "billing.no_results_desc": "Adjust your filters",
    "billing.reset": "Reset",
    "billing.count": "invoice",
    "billing.count_plural": "invoices",
    "billing.intervention": "Intervention",
    "billing.col_paid_missions": "Paid missions",
    "billing.col_net_revenue": "Net revenue",
    "billing.col_commissions": "Commissions deducted",
    "billing.export_csv": "Export CSV",
    "billing.export_pdf": "Export PDF",
    "billing.csv_title": "CSV Export",
    "billing.csv_desc": "Invoices exported to CSV.",
    "billing.pdf_title": "PDF Export",
    "billing.pdf_desc": "Invoices exported to PDF.",

    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "Global operational performance overview",
    "analytics.avg_time": "Avg. intervention time",
    "analytics.missions_per_day": "Missions per day",
    "analytics.success_rate": "Success rate",
    "analytics.active_providers": "Active providers",
    "analytics.daily_missions": "Daily missions",
    "analytics.response_time": "Avg. response time (min)",
    "analytics.zone_distribution": "Distribution by zone",
    "analytics.hourly_distribution": "Hourly distribution",
    "analytics.top_providers": "Most active providers",
    "analytics.by_service_type": "Interventions by type",
    "analytics.7_days": "7 days",
    "analytics.30_days": "30 days",
    "analytics.90_days": "90 days",
    "analytics.total": "Total",
    "analytics.completed": "Completed",
    "analytics.minutes": "minutes",
    "analytics.missions": "missions",
    "analytics.this_week": "this week",
    "analytics.on_mission_today": "on mission today",
    "analytics.avg_time_label": "avg. time",
    "analytics.export_csv": "Export CSV",
    "analytics.export_pdf": "Export PDF",
    "analytics.csv_title": "CSV Export",
    "analytics.csv_desc": "Mission report exported to CSV.",
    "analytics.pdf_title": "PDF Export",
    "analytics.pdf_desc": "Analytics report exported to PDF.",

    // Audit Logs
    "audit.title": "Audit Logs",
    "audit.subtitle": "Full administrative action history",
    "audit.assign": "Assignment",
    "audit.status_change": "Status change",
    "audit.create": "Creation",
    "audit.delete": "Deletion",
    "audit.update": "Update",
    "audit.login": "Login",
    "audit.all_actions": "All",
    "audit.actor": "Actor",
    "audit.action": "Action",
    "audit.description": "Description",
    "audit.target": "Target",
    "audit.date": "Date",
    "audit.search": "Search...",
    "audit.no_results": "No logs found",
    "audit.no_results_desc": "Adjust your filters",
    "audit.reset": "Reset",
    "audit.count": "entry",
    "audit.count_plural": "entries",

    // Settings
    "settings.title": "Settings",
    "settings.platform": "Platform",
    "settings.users": "Users",
    "settings.notifications": "Notifications",
    "settings.system": "System",
    "settings.platform_config": "Platform Configuration",
    "settings.platform_name": "Platform Name",
    "settings.support_email": "Support Email",
    "settings.timezone": "Timezone",
    "settings.currency": "Currency",
    "settings.default_language": "Default Language",
    "settings.coverage_radius": "Default Coverage Radius (km)",
    "settings.auto_approve": "Auto-approve Service Providers",
    "settings.auto_approve_desc": "Skip manual review for new registrations",
    "settings.save_changes": "Save Changes",
    "settings.saved": "saved",
    "settings.saved_desc": "Your changes have been applied.",
    "settings.invite_admin": "Invite Admin User",
    "settings.invite_email": "Email address",
    "settings.invite": "Invite",
    "settings.admin_users": "Admin Users",
    "settings.remove_user": "Remove {name}?",
    "settings.remove_desc": "This will revoke their admin access immediately.",
    "settings.remove": "Remove",
    "settings.invitation_sent": "Invitation sent",
    "settings.invited_as": "Invited {email} as {role}.",
    "settings.user_removed": "User removed",
    "settings.user_removed_desc": "The admin user has been removed.",
    "settings.email_required": "Email required",
    "settings.email_required_desc": "Please enter an email address.",
    "settings.admin_notifications": "Admin Notifications",
    "settings.notif_registrations": "New registrations",
    "settings.notif_registrations_desc": "Alert when a service provider or fleet manager registers",
    "settings.notif_interventions": "Intervention alerts",
    "settings.notif_interventions_desc": "Critical intervention updates and escalations",
    "settings.notif_errors": "System errors",
    "settings.notif_errors_desc": "Server errors and downtime notifications",
    "settings.notif_weekly": "Weekly reports",
    "settings.notif_weekly_desc": "Summary of platform activity every Monday",
    "settings.notif_daily": "Daily digest",
    "settings.notif_daily_desc": "Daily summary email of key metrics",
    "settings.notif_slack": "Slack integration",
    "settings.notif_slack_desc": "Forward alerts to a Slack channel",
    "settings.system_prefs": "System Preferences",
    "settings.session_timeout": "Session Timeout (minutes)",
    "settings.data_retention": "Data Retention (days)",
    "settings.maintenance_mode": "Maintenance Mode",
    "settings.maintenance_desc": "Temporarily disable access for non-admin users",
    "settings.danger_zone": "Danger Zone",
    "settings.danger_desc": "Purge all data or reset the platform to factory defaults. These actions are irreversible.",
    "settings.reset_platform": "Reset Platform",
    "settings.reset_confirm": "Reset entire platform?",
    "settings.reset_desc": "This will delete all accounts, interventions, invoices, and configuration. This cannot be undone.",
    "settings.reset_action": "Reset Everything",

    // Profile
    "profile.title": "My Profile",
    "profile.subtitle": "Manage your personal information.",
    "profile.personal_info": "Personal information",
    "profile.update_success": "Profile updated!",
    "profile.update_error": "Error updating profile.",
    "profile.change_avatar": "Change avatar",
    "profile.full_name": "Full name",
    "profile.email": "Email",
    "profile.edit": "Edit",
    "profile.save": "Save",
    "profile.security": "Security",
    "profile.password": "Password",
    "profile.password_desc": "Send a password reset email",
    "profile.change_password": "Change",
    "profile.online": "Online",
    "profile.upload_error": "Error uploading file.",
    "profile.avatar_updated": "Avatar updated!",
    "profile.avatar_error": "Error updating avatar.",
    "profile.reset_sent": "Password reset email sent!",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.loading": "Loading...",
    "common.no_results": "No results",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.yes": "Yes",
    "common.no": "No",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.date": "Date",
    "common.required_fields": "Required fields",
    "common.confirm_delete": "Confirm deletion",
    "common.delete_warning": "This action is irreversible.",

    // Auth
    "auth.login": "Sign in",
    "auth.signup": "Sign up",
    "auth.logout": "Sign out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgot_password": "Forgot password?",
    "auth.no_account": "No account?",
    "auth.has_account": "Already have an account?",
    "auth.welcome": "Welcome back",
    "auth.welcome_subtitle": "Sign in to your account",
    "auth.signup_title": "Create an account",
    "auth.signup_subtitle": "Sign up to access the platform",
    "auth.forgot_title": "Forgot password",
    "auth.forgot_subtitle": "Enter your email to reset",
    "auth.name": "Full name",
    "auth.verify_email": "Check your email to confirm your account.",
    "auth.reset_sent": "Reset email sent.",
    "auth.google": "Continue with Google",
    "auth.or": "or",
    "auth.reset_password": "Reset password",
    "auth.logging_in": "Signing in...",
    "auth.signing_up": "Signing up...",
    "auth.sending": "Sending...",
    "auth.send_link": "Send link",
    "auth.back_to_login": "Back to login",

    // Role guard
    "guard.restricted": "Restricted access",
    "guard.no_permission": "You don't have the necessary permissions to access this page.",
    "guard.required_roles": "Required roles",

    // Admin Roles
    "roles.title": "Role Management",
    "roles.subtitle": "Manage platform user permissions.",
    "roles.search": "Search for a user...",
    "roles.user_col": "User",
    "roles.current_role": "Current role",
    "roles.action": "Action",
    "roles.yourself": "Yourself",
    "roles.updated": "Role updated!",
    "roles.assigned": "Role assigned!",
    "roles.admins": "Admins",
    "roles.moderators": "Moderators",
    "roles.users": "Users",
    "roles.no_user": "No users found.",
    "roles.access_denied": "Access denied",
    "roles.admin_required": "You must have the Admin role to access this page.",

    // Not found
    "notfound.title": "404",
    "notfound.message": "Oops! Page not found",
    "notfound.back_home": "Return to Home",

    // Status labels
    "status.pending": "Pending",
    "status.assigned": "Assigned",
    "status.en_route": "En route",
    "status.arrived": "Arrived",
    "status.in_progress": "In progress",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.active": "Active",
    "status.inactive": "Inactive",
    "status.paid": "Paid",
    "status.overdue": "Overdue",

    // Days
    "day.mon": "Mon",
    "day.tue": "Tue",
    "day.wed": "Wed",
    "day.thu": "Thu",
    "day.fri": "Fri",
    "day.sat": "Sat",
    "day.sun": "Sun",

    // Activity
    "activity.account_created": "Account created",
    "activity.submitted_review": "Submitted for review",
    "activity.account_rejected": "Account rejected",
    "activity.ago_5min": "5 min ago",
    "activity.ago_23min": "23 min ago",
    "activity.ago_1h": "1h ago",
    "activity.ago_3h": "3h ago",
    "activity.ago_5h": "5h ago",

    // Accounts
    "accounts.title": "Accounts",
    "accounts.subtitle": "Manage provider and fleet manager registrations.",
    "accounts.new": "New account",
    "accounts.search": "Search by name, email...",
    "accounts.filter_all": "All",
    "accounts.filter_sp": "Service Providers",
    "accounts.filter_fm": "Fleet Managers",
    "accounts.filter_all_status": "All Status",
    "accounts.export_csv": "Export CSV",
    "accounts.type_sp": "Provider",
    "accounts.type_fm": "Manager",
    "accounts.company": "Company",
    "accounts.type": "Type",
    "accounts.email": "Email",
    "accounts.submitted": "Submitted",
    "accounts.status": "Status",
    "accounts.actions": "Actions",
    "accounts.of": "of",
    "accounts.accounts": "accounts",
    "accounts.previous": "Previous",
    "accounts.next": "Next",
    "accounts.no_results": "No accounts found",
    "accounts.no_results_desc": "Try adjusting your filters",
    "accounts.reset": "Reset",
    "accounts.edit_title": "Edit account",
    "accounts.create_title": "New account",
    "accounts.company_label": "Company *",
    "accounts.company_placeholder": "Company name",
    "accounts.type_label": "Type",
    "accounts.type_fleet": "Fleet Manager",
    "accounts.email_label": "Email *",
    "accounts.phone_label": "Phone",
    "accounts.cancel": "Cancel",
    "accounts.save": "Save",
    "accounts.create": "Create",
    "accounts.required_fields": "Required fields",
    "accounts.required_fields_desc": "Company and email are required.",
    "accounts.updated": "Account updated",
    "accounts.updated_desc": "has been modified.",
    "accounts.created": "Account created",
    "accounts.created_desc": "added pending approval.",
    "accounts.deleted": "Account deleted",
    "accounts.deleted_desc": "has been deleted.",
    "accounts.approved_toast": "Account approved",
    "accounts.approved_toast_desc": "The account has been activated.",
    "accounts.rejected_toast": "Account rejected",
    "accounts.rejected_toast_desc": "The account has been refused.",
    "accounts.delete_title": "Delete",
    "accounts.delete_desc": "This action is irreversible. The account will be permanently deleted.",
    "accounts.delete": "Delete",
    "accounts.overview": "Overview",
    "accounts.technicians_tab": "Technicians",
    "accounts.services_tab": "Services",
    "accounts.documents_tab": "Documents",
    "accounts.reg_number": "Registration no.",
    "accounts.submission_date": "Submission date",
    "accounts.approve": "Approve",
    "accounts.edit": "Edit",
    "accounts.view": "View",
    "accounts.reject": "Reject",
    "accounts.technicians_count": "registered technicians",
    "accounts.services_list": "Towing, Tire change, Battery",
    "accounts.services_pricing": "Rates: €45 – €180 per intervention",
    "accounts.documents_count": "uploaded documents",
    "accounts.documents_list": "Insurance, License, Registration, Certificate",

    // Providers
    "providers.title": "Providers",
    "providers.registered": "registered providers.",
    "providers.search": "Search...",
    "providers.all": "All",
    "providers.approved": "Approved",
    "providers.pending": "Pending",
    "providers.add": "Add",
    "providers.status_approved": "Approved",
    "providers.status_pending": "Pending",
    "providers.technicians": "Technicians",
    "providers.completed": "Completed",
    "providers.active": "Active",
    "providers.view": "View",
    "providers.edit_title": "Edit provider",
    "providers.create_title": "New provider",
    "providers.name_label": "Name *",
    "providers.name_placeholder": "Provider name",
    "providers.contact_label": "Contact",
    "providers.contact_placeholder": "Contact name",
    "providers.email_label": "Email *",
    "providers.city_label": "City",
    "providers.services_label": "Services",
    "providers.cancel": "Cancel",
    "providers.save": "Save",
    "providers.create": "Create",
    "providers.required_fields": "Required fields",
    "providers.required_fields_desc": "Name and email are required.",
    "providers.updated": "Provider updated",
    "providers.updated_desc": "modified.",
    "providers.created": "Provider created",
    "providers.created_desc": "added.",
    "providers.deleted": "Provider deleted",
    "providers.deleted_desc": "deleted.",
    "providers.delete_title": "Delete",
    "providers.delete_desc": "This action is irreversible.",
    "providers.delete": "Delete",
    "providers.member_since": "Member since",
    "providers.contact": "Contact",
    "providers.coverage_zone": "Coverage zone",
    "providers.radius": "Radius",
    "providers.performance": "Performance",
    "providers.completed_label": "Completed",
    "providers.active_label": "Active",
    "providers.technicians_label": "Technicians",
    "providers.response_time": "Response time",
    "providers.edit": "Edit",

    // Fleet Managers
    "fleet.title": "Fleet Managers",
    "fleet.registered": "registered managers.",
    "fleet.search": "Search...",
    "fleet.all": "All",
    "fleet.active": "Active",
    "fleet.inactive": "Inactive",
    "fleet.add": "Add",
    "fleet.total_vehicles": "Total vehicles",
    "fleet.active_fleets": "Active fleets",
    "fleet.ongoing_interventions": "Ongoing interventions",
    "fleet.company": "Company",
    "fleet.contact": "Contact",
    "fleet.city": "City",
    "fleet.vehicles": "Vehicles",
    "fleet.active_col": "Active",
    "fleet.total": "Total",
    "fleet.status": "Status",
    "fleet.actions": "Actions",
    "fleet.status_active": "Active",
    "fleet.status_inactive": "Inactive",
    "fleet.edit_title": "Edit manager",
    "fleet.create_title": "New manager",
    "fleet.company_label": "Company *",
    "fleet.contact_label": "Contact",
    "fleet.city_label": "City",
    "fleet.email_label": "Email *",
    "fleet.phone_label": "Phone",
    "fleet.vehicles_label": "Vehicles",
    "fleet.cancel": "Cancel",
    "fleet.save": "Save",
    "fleet.create": "Create",
    "fleet.required_fields": "Required fields",
    "fleet.required_fields_desc": "Company and email are required.",
    "fleet.updated": "Manager updated",
    "fleet.updated_desc": "modified.",
    "fleet.created": "Manager created",
    "fleet.created_desc": "added.",
    "fleet.deleted": "Manager deleted",
    "fleet.deleted_desc": "deleted.",
    "fleet.delete_title": "Delete",
    "fleet.delete_desc": "This action is irreversible.",
    "fleet.delete": "Delete",
    "fleet.member_since": "Member since",
    "fleet.vehicles_stat": "Vehicles",
    "fleet.active_stat": "Active",
    "fleet.total_missions": "Total missions",
    "fleet.monthly_avg": "Monthly avg",
    "fleet.fleet_types": "Fleet types",
    "fleet.edit": "Edit",
    "accounts.temp_password_title": "Account created successfully",
    "accounts.temp_password_desc": "Please note the temporary password below. It will not be shown again.",
    "accounts.temp_password_label": "Temporary password",
    "accounts.mobile_access_title": "Mobile App Access",
    "accounts.mobile_access_desc": "Information required for the company to connect to the field app.",
    "accounts.company_code": "Company Code",
    "accounts.reset_password": "Reset Password",
    "accounts.reset_password_confirm": "Do you want to reset the password for this account? A new temporary password will be generated.",
    "accounts.copy_all": "Copy login info",
    "accounts.credentials_copied": "Login info copied!",
  },
};

const STORAGE_KEY = "fleet-rescue-language";

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored === "en" || stored === "fr") return stored;
    } catch {}
    return "fr";
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch {}
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);

  const t = (key: string): string => {
    return translations[language][key] || translations.fr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
